# Build the docker file inside the backend and frontend directories plus build a 
# container named slither pulling it from trailofbits/eth-security-toolbox

version: '3.8'
services:
  slither:
    image: trailofbits/eth-security-toolbox
    container_name: slither
    working_dir: /app/backend
    command: ["slither", "--solc-remaps", "https://raw.githubusercontent.com/ethereum/remix-project/master/packages/remix-solidity/src/solidity-compiler/remappings.txt", "."]
    binds:
      - ./hardhat:/hardhat
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:  
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    command: ["npm", "start"]
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - slither
      - frontend

networks:
  default:
    driver: bridge