version: '3.8'
services:
  slither:
    image: trailofbits/eth-security-toolbox
    container_name: slither
    volumes:
      - ./hardhat:/shared
    command: tail -f /dev/null

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development

  backend:  
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./hardhat:/hardhat
      # Bind also the docker.sock file to be able to run docker commands from inside the container
      - /var/run/:/var/run/
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge