# Build the docker file inside the backend and frontend directories plus build a 
# container named slither pulling it from trailofbits/eth-security-toolbox

version: '3.8'
services:
  slither:
    image: trailofbits/eth-security-toolbox
    container_name: slither
    working_dir: /app/backend
    volumes:
      - ./hardhat:/shared
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:  
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./hardhat:/hardhat
      # Bind also the docker.sock file to be able to run docker commands from inside the container
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - slither
      - frontend

networks:
  default:
    driver: bridge