version: '3.8'
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development

  backend:  
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./hardhat:/hardhat
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge